project:
  type: website
  preview:
    port: 4200

website:
  favicon: assets/img/logos/favicon.svg
  search:
    location: sidebar
    type: textbox
    copy-button: true

  navbar:
    pinned: true
  page-navigation: true
  bread-crumbs: true

  title: "APEx - Documentation Portal"

  sidebar:
    - id: "index"
      tools:
        - icon: github
          href: https://github.com/ESA-APEx/apex_toolbox_documentation
      style: "floating"
      #collapse-level: 2
      contents:
        - href: docs/index.qmd
          text: Welcome
        - text: FORCE with openEO on CDSE
          href: docs/force/index.qmd
    - id: "force"
      style: "floating"
      collapse-level: 2
      tools:
        - icon: github
          menu:
            - text: APEx toolbox documentation source code
              href: https://github.com/ESA-APEx/apex_toolbox_documentation
            - text: FORCE integration source code
              href: https://github.com/bcdev/apex-force-openeo
            - text: FORCE toolbox source code
              href: https://github.com/davidfrantz/force
      contents:
        - href: docs/index.qmd
          text: Welcome
        - text: FORCE with openEO on CDSE
          contents: docs/force/**

format:
  html:
    page-layout: full
    theme: [cosmo, css/custom.scss]
    scss: true
    highlight-style: solarized
    include-in-header:
      - html/esa-header.html
    link-external-newwindow: false
